--------------------------------------------------
-- 1. KPI_TEMPLATE
--------------------------------------------------
CREATE TABLE KPI_TEMPLATE(
    NAM NUMBER(4),
    CHI_NHANH VARCHAR2(100),
    KPI NUMBER(18,2)
);

--------------------------------------------------
-- 2. KHACH_HANG
--------------------------------------------------
CREATE TABLE KHACH_HANG (
    MA_KH VARCHAR2(50) PRIMARY KEY,
    KHACH_HANG VARCHAR2(255)
);

--------------------------------------------------
-- 3. SAN_PHAM
--------------------------------------------------
CREATE TABLE SAN_PHAM (
    MA_SAN_PHAM VARCHAR2(50) PRIMARY KEY,
    SAN_PHAM VARCHAR2(255),
    NHOM_SAN_PHAM VARCHAR2(255)
);

--------------------------------------------------
-- 4. NHAN_VIEN
--------------------------------------------------
CREATE TABLE NHAN_VIEN (
    MA_NHAN_VIEN_BAN VARCHAR2(50) PRIMARY KEY,
    NHAN_VIEN_BAN VARCHAR2(255)
);

--------------------------------------------------
-- 5. CHI_NHANH
--------------------------------------------------
CREATE TABLE CHI_NHANH (
    MA_CHI_NHANH VARCHAR2(50) PRIMARY KEY,
    TEN_CHI_NHANH VARCHAR2(255),
    TINH_THANH_PHO VARCHAR2(255)
);

--------------------------------------------------
-- 6. DU_LIEU_BAN_HANG
--------------------------------------------------
CREATE TABLE DU_LIEU_BAN_HANG (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NGAY_HACH_TOAN DATE,
    SO_DON_HANG VARCHAR2(100),
    MA_KH VARCHAR2(50),
    MA_SAN_PHAM VARCHAR2(50),
    SO_LUONG_BAN NUMBER(18,2),
    DON_GIA NUMBER(18,2),
    DOANH_THU NUMBER(18,2),
    GIA_VON_HANG_HOA NUMBER(18,2),
    MA_NHAN_VIEN_BAN VARCHAR2(50),
    MA_CHI_NHANH VARCHAR2(50),

    CONSTRAINT FK_BAN_HANG_KH FOREIGN KEY (MA_KH)
        REFERENCES KHACH_HANG(MA_KH),

    CONSTRAINT FK_BAN_HANG_SP FOREIGN KEY (MA_SAN_PHAM)
        REFERENCES SAN_PHAM(MA_SAN_PHAM),

    CONSTRAINT FK_BAN_HANG_NV FOREIGN KEY (MA_NHAN_VIEN_BAN)
        REFERENCES NHAN_VIEN(MA_NHAN_VIEN_BAN),

    CONSTRAINT FK_BAN_HANG_CN FOREIGN KEY (MA_CHI_NHANH)
        REFERENCES CHI_NHANH(MA_CHI_NHANH)
);

--------------------------------------------------
-- Index để query nhanh hơn
--------------------------------------------------
CREATE INDEX IDX_BAN_HANG_NGAY ON DU_LIEU_BAN_HANG(NGAY_HACH_TOAN);
CREATE INDEX IDX_BAN_HANG_DON_HANG ON DU_LIEU_BAN_HANG(SO_DON_HANG);
CREATE INDEX IDX_BAN_HANG_MA_KH ON DU_LIEU_BAN_HANG(MA_KH);
CREATE INDEX IDX_BAN_HANG_MA_SP ON DU_LIEU_BAN_HANG(MA_SAN_PHAM);